# importing necessary libraries

In [81]:
import pandas as pd
import numpy as np
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer, WordNetLemmatizer
import matplotlib.pyplot as plt
%matplotlib inline

# Loading the csv file

In [6]:
data = pd.read_csv('companydata\company_reviews.csv')

In [85]:
data.head()

,name,rating,reviews,description,happiness,ceo_approval,ceo_count,ratings,locations,roles,...,interview_difficulty,interview_duration,interview_count,headquarters,employees,industry,revenue,website,name_lower,reviews_lower
0,Sitel,NaN,NaN,"Sitel Group’s 75,000 people across the globe c...","{'Work Happiness Score': '55', 'Achievement': ...",70%,"CEO Approval is based on 4,612 ratings","{'Work/Life Balance': '3.4', 'Compensation/Ben...","{'Paradise, NV': '5.0', 'Pioneer, OH': '4.7', ...","{'Tier 1 Agent': '5.0', 'Director of Operation...",...,Easy,About a day or two,Based on 645 interviews,"600 Brickell Ave Miami, FL 33131 Vereinigte St...","10,000+",Telecommunications,$1B to $5B (USD),Twitter\nFacebook\nSitel website,sitel,NaN
1,Meadowbrook Rehabilitation,3.7,21 reviews,You'll work with the most experienced and loya...,{},NaN,NaN,"{'Work/Life Balance': '4.1', 'Compensation/Ben...",{},{},...,Easy,NaN,Based on 5 interviews,Illinois,NaN,Healthcare,NaN,Meadowbrook Rehabilitation website,meadowbrook rehabilitation,21 reviews
2,Intermountain,4.0,23 reviews,Why Intermountain?\n\nWe Bring Hope\n\nWith ou...,{},88%,CEO Approval is based on 17 ratings,"{'Work/Life Balance': '3.5', 'Compensation/Ben...",{},{},...,Medium,About a day or two,Based on 8 interviews,"Headquarters: 3240 Dredge Dr. Helena, MT 59602",201 to 500,Healthcare,$5M to $25M (USD),Twitter\nFacebook\nIntermountain website,intermountain,23 reviews
3,Smith & Nephew,NaN,NaN,It's more than business at Smith+Nephew - it's...,"{'Work Happiness Score': '65', 'Purpose': '71'...",76%,CEO Approval is based on 374 ratings,"{'Work/Life Balance': '3.5', 'Compensation/Ben...","{'Largo, FL': '4.5', 'Chicago, IL': '4.3', 'Sa...","{'Packaging Technician': '5.0', 'Senior Associ...",...,Medium,About a week,Based on 116 interviews,"Building 5, Croxley Park, Hatters Lane, Watfor...","10,000+",Healthcare,$1B to $5B (USD),Twitter\nFacebook\nSmith & Nephew website,smith & nephew,NaN
4,Reverse Mortgage Funding,4.1,19 reviews,Reverse Mortgage Funding LLC is committed to e...,{},NaN,NaN,"{'Work/Life Balance': '4.2', 'Compensation/Ben...",{},{},...,NaN,NaN,Based on 5 interviews,Bloomfield,11 to 50,Financial Services,$5M to $25M (USD),Reverse Mortgage Funding website,reverse mortgage funding,19 reviews

# Removing stopwords from the column called Description

In [46]:
nltk.download('stopwords')
from nltk.corpus import stopwords
",".join(stopwords.words('english'))
stop_words=set(stopwords.words('english'))

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\kartelloh\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [111]:
def remove_stop(x):
    return",".join([word for word in str(x).split()if word not in stop_words])
data["description"].head().apply(lambda x : remove_stop(x))

0    sitel,group’s,75,000,people,across,globe,conne...
1    work,experienced,loyal,health,care,professiona...
2    intermountain?,bring,hope,holistic,,integrated...
3    business,smith+nephew,-,personal.,every,day,,c...
4    reverse,mortgage,funding,llc,committed,enhanci...
Name: description, dtype: object

# Convert text to lowercase in the description column
we are going to convert the text in Description column into lower case

In [116]:
data["description"]=data["description"].str.lower()
data["description"].head()

0    sitel group’s 75,000 people across the globe c...
1    you'll work with the most experienced and loya...
2    why intermountain?\n\nwe bring hope\n\nwith ou...
3    it's more than business at smith+nephew - it's...
4    reverse mortgage funding llc is committed to e...
Name: description, dtype: object

# Removing special characters from the Locations column

In [131]:
data['locations'] = data['locations'].str.replace('\W', '', regex=True)
data['locations'].head()

0    ParadiseNV50PioneerOH47MoroccoIN46KingstonNY46...
1
2
3    LargoFL45ChicagoIL43SanAntonioTX43SaintPetersb...
4
Name: locations, dtype: object

# Remove URLs from the column "websites"

In [133]:
data['website'] = data['website'].replace(to_replace=r'^https?:\/\/.*[\r\n]*',value='',regex=True)

data['website'].head()

0             Twitter\nFacebook\nSitel website
1           Meadowbrook Rehabilitation website
2     Twitter\nFacebook\nIntermountain website
3    Twitter\nFacebook\nSmith & Nephew website
4             Reverse Mortgage Funding website
Name: website, dtype: object

# Tokenizing data in the column "description"

In [145]:
nltk.word_tokenize(data["description"][0])

['sitel',
 'group',
 '’',
 's',
 '75,000',
 'people',
 'across',
 'the',
 'globe',
 'connect',
 'many',
 'of',
 'the',
 'world',
 '’',
 's',
 'best-known',
 'brands',
 'with',
 'their',
 'customers',
 '-',
 '3.5',
 'million',
 'times',
 'every',
 'day',
 '.',
 'as',
 'a',
 'global',
 'customer',
 'experience',
 '(',
 'cx',
 ')',
 'management',
 'leader',
 ',',
 'we',
 'apply',
 'our',
 '30+',
 'years',
 'of',
 'industry-leading',
 'experience',
 'and',
 'the',
 'entrepreneurial',
 'spirit',
 'of',
 'our',
 'group',
 '’',
 's',
 'founders',
 'to',
 'deliver',
 'omnichannel',
 'experiences',
 'through',
 'voice',
 ',',
 'chat',
 ',',
 'social',
 'media',
 'and',
 'more',
 'to',
 'customers',
 'of',
 'our',
 '400+',
 'clients',
 'across',
 'all',
 'verticals',
 '–',
 'from',
 'fortune',
 '500',
 'companies',
 'to',
 'local',
 'startups',
 '.',
 'we',
 'are',
 'redefining',
 'the',
 'contact',
 'center',
 'and',
 'improving',
 'business',
 'results',
 'by',
 'pairing',
 'innovative',
 'solutions',
 '-',
 'such',
 'as',
 'self-care',
 'and',
 'automation',
 '-',
 'with',
 'the',
 'human',
 'touch',
 ',',
 'emotion',
 'and',
 'empathy',
 'of',
 'our',
 'people',
 '.',
 'as',
 'a',
 'cx',
 'platform',
 ',',
 'we',
 'are',
 'powered',
 'by',
 'experts',
 'to',
 'deliver',
 'tailored',
 'cx',
 'solutions',
 'to',
 'fit',
 'our',
 'clients',
 '’',
 'needs',
 'through',
 'our',
 'consultative',
 ',',
 'customer-centric',
 'approach',
 'adding',
 'value',
 'at',
 'every',
 'touchpoint',
 '-',
 'regardless',
 'of',
 'location',
 ',',
 'channel',
 'or',
 'time',
 'of',
 'day',
 '.',
 'learn',
 'more',
 'at',
 'www.sitel.com',
 'and',
 'connect',
 'with',
 'us',
 'on',
 'facebook',
 ',',
 'linkedin',
 'and',
 'twitter',
 '.',
 '–',
 'less']